version: '3.7'

services:
  chatbot:
    container_name: chatbot
    restart: always
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend/:/app/:cached  # Mount code to allow for hot reloading
      - ./.docker/.ipython:/root/.ipython:cached

    labels:
      # Enable Traefik for this specific "chatbot" service
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot.rule=Host(`kwagchatbot.xyz`) && PathPrefix(`/`)"
      - "traefik.http.routers.chatbot.service=chatbot"
      - "traefik.http.routers.chatbot.entrypoints=web-secured"
      - "traefik.http.routers.chatbot.tls.certresolver=leresolver"
      - "traefik.http.routers.chatbot.tls=true"
      - "traefik.http.services.chatbot.loadbalancer.server.port=8090"
      - "traefik.docker.network=traefik-public"
    ports:
      - '8090:8000'
    networks:
    # Use the public network created to be shared between Traefik and\
    # any other service that needs to be publicly available with HTTPS
     - traefik-public

networks:
  traefik-public:
        external: true
